on:
  push:
  pull_request:
    branches: [master]
jobs:
  verify-linux:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install development dependencies
        run: shards install
      - name: Run tests
        run: |
          export CONFIG_NAME="${{ vars.CONFIG_NAME }}"
          export CONFIG_URL="${{ vars.CONFIG_URL }}"
          export CONFIG_KEY="${{ secrets.CONFIG_KEY }}"
          make lint spec
      - name: Make sure the files are formatted
        run: crystal tool format --check
